version: "3.8"
services:
  service-discovery:
    build: ./service-discovery
    ports:
      - "8761:8761"
  gateway-service:
    build: ./gateway-service
    ports:
      - "7070:8080"
    environment:
      - EUREKA_CLIENT_URL=${SERVICE_DISCOVERY_URL}
    restart: always
  client-service:
    build: ./client-service
    expose:
      - "8080"
    restart: always
    environment:
      - DATABASE_USER=${USER_DB}
      - DATABASE_PASSWORD=${PASSWORD_DB}
      - DATABASE_URL=jdbc:postgresql://client-db:5432/${CLIENT_DB}
      - EUREKA_CLIENT_URL=${SERVICE_DISCOVERY_URL}
    depends_on:
      - service-discovery
      - client-db
  client-db:
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_USER=${USER_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_DB=${CLIENT_DB}
    ports:
      - "7001:5432"
    restart: always
    depends_on:
      - bank-processor
  bank-processor:
    build: ./bank-processor
    expose:
      - "8080"
    restart: always
    environment:
      - DATABASE_USER=${USER_DB}
      - DATABASE_PASSWORD=${PASSWORD_DB}
      - DATABASE_URL=jdbc:postgresql://bank-db:5432/${BANK_DB}
      - EUREKA_CLIENT_URL=${SERVICE_DISCOVERY_URL}
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - bank-db
      - service-discovery
  bank-db:
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_USER=${USER_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_DB=${BANK_DB}
    ports:
      - "7002:5432"
    restart: always