version: "3.8"
services:
  client-service:
    build: ./client-service
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DATABASE_USER=${USER_DB}
      - DATABASE_PASSWORD=${PASSWORD_DB}
      - DATABASE_URL=jdbc:postgresql://client-db:5432/${CLIENT_DB}
    depends_on:
      - client-db
  client-db:
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_USER=${USER_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_DB=${CLIENT_DB}
    ports:
      - "7001:5432"
    restart: always